CREATE TABLE IF NOT EXISTS `usuarios` (
  `usuario_id` int(11) NOT NULL AUTO_INCREMENT,
  `usuario_nombre` varchar(40) NOT NULL,
  `usuario_apellido` varchar(40) NOT NULL,
  `usuario_empresa` varchar(50) NOT NULL,
  `usuario_calle` varchar(30)  NOT NULL,
  `usuario_no_ext` varchar(20) NOT NULL,
  `usuario_no_int` varchar(20) DEFAULT NULL,
  `usuario_colonia` varchar(30) DEFAULT NULL,
  `usuario_localidad` varchar(30) DEFAULT NULL, 
  `usuario_rfc` varchar(20) DEFAULT NULL,
  `usuario_cp` int(10) NOT NULL,
  `usuario_ap` int(6) DEFAULT NULL,
  `usuario_ciudad` varchar(30) NOT NULL,
  `usuario_estado_id` int(2) NOT NULL,
  `usuario_estado` varchar(20) DEFAULT NULL,
  `usuario_pais_id` varchar(20) DEFAULT NULL,
  `usuario_lada` int(6) NOT NULL,
  `usuario_telefono` int(15) NOT NULL,
  `usuario_fax` int(15) DEFAULT NULL,
  `usuario_email` varchar(100) NOT NULL,
  `usuario_username` varchar(20) DEFAULT NULL,
  `usuario_password` varchar(20) NOT NULL,
  `usuario_fecha_inscripcion` date DEFAULT NULL,
  `usuario_fecha_activacion` date DEFAULT NULL,
  `usuario_fecha_vencimiento` date DEFAULT NULL,
  `usuario_isactive` int(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`usuario_id`)
)